[package]
name = "npm-readme-client"
description = "interface to npm pkg readmes in rust"
repository = "https://github.com/npm/rust-readme-client"
version = "0.3.0"
authors = ["Ashley Williams <ashley666ashley@gmail.com>"]
license = "MIT"

[dependencies]
dotenv = "0.10.1"
reqwest = "0.8.1"
